######################################################################################################################
##                                                       Spring Configuration
######################################################################################################################
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}
    username: ${db.username}
    password:

######################################################################################################################
##                                                       Database Configuration
######################################################################################################################
db:
  name : hikari-core-be
  host : localhost
  port : 3306
  username : root
  password :
  auto-reconnect : true
  ssl : false
